import { Dimensions, PixelRatio, Platform, StyleSheet } from "react-native";
import { scaler } from "./config.styles";

const fontNormalize = (size: number) => PixelRatio.roundToNearestPixel((size * Dimensions.get("window").width) / 375);

export const staticStyles = StyleSheet.create({
  // Flex
  flex_1: { flex: 1 },
  flex_2: { flex: 2 },
  flex_3: { flex: 3 },
  aspect_square: { aspectRatio: 1 },
  row: { flexDirection: "row" },
  column: { flexDirection: "column" },
  wrap: { flexWrap: "wrap" },
  no_wrap: { flexWrap: "nowrap" },

  // Alignment
  justify_start: { justifyContent: "flex-start" },
  justify_center: { justifyContent: "center" },
  justify_end: { justifyContent: "flex-end" },
  justify_between: { justifyContent: "space-between" },
  justify_around: { justifyContent: "space-around" },
  justify_evenly: { justifyContent: "space-evenly" },
  items_start: { alignItems: "flex-start" },
  items_center: { alignItems: "center" },
  items_end: { alignItems: "flex-end" },
  items_stretch: { alignItems: "stretch" },
  items_baseline: { alignItems: "baseline" },
  self_start: { alignSelf: "flex-start" },
  self_center: { alignSelf: "center" },
  self_end: { alignSelf: "flex-end" },
  self_stretch: { alignSelf: "stretch" },

  // Border Radius
  rounded_none: { borderRadius: 0 },
  rounded_xs: { borderRadius: scaler.width(2) },
  rounded_sm: { borderRadius: scaler.width(4) },
  rounded_md: { borderRadius: scaler.width(6) },
  rounded_lg: { borderRadius: scaler.width(12) },
  rounded_xl: { borderRadius: scaler.width(24) },
  rounded_full: { borderRadius: 9999 },

  // Border Width
  border_0: { borderWidth: 0 },
  border_1: { borderWidth: 1 },
  border_2: { borderWidth: 2 },
  border_4: { borderWidth: 4 },
  border_t_1: { borderTopWidth: 1 },
  border_b_1: { borderBottomWidth: 1 },
  border_l_1: { borderLeftWidth: 1 },
  border_r_1: { borderRightWidth: 1 },

  // Gap
  gap_xs: { gap: scaler.width(1) },
  gap_sm: { gap: scaler.width(2) },
  gap_md: { gap: scaler.width(4) },
  gap_lg: { gap: scaler.width(6) },
  gap_xl: { gap: scaler.width(8) },

  // Margin
  m_xs: { margin: scaler.width(1) },
  m_sm: { margin: scaler.width(2) },
  m_md: { margin: scaler.width(4) },
  m_lg: { margin: scaler.width(6) },
  m_xl: { margin: scaler.width(8) },
  mx_xs: { marginHorizontal: scaler.width(1) },
  mx_sm: { marginHorizontal: scaler.width(2) },
  mx_md: { marginHorizontal: scaler.width(4) },
  mx_lg: { marginHorizontal: scaler.width(6) },
  mx_xl: { marginHorizontal: scaler.width(8) },
  my_xs: { marginVertical: scaler.height(0.5) },
  my_sm: { marginVertical: scaler.height(1) },
  my_md: { marginVertical: scaler.height(2) },
  my_lg: { marginVertical: scaler.height(3) },
  my_xl: { marginVertical: scaler.height(4) },
  mt_xs: { marginTop: scaler.height(0.5) },
  mt_sm: { marginTop: scaler.height(1) },
  mt_md: { marginTop: scaler.height(2) },
  mt_lg: { marginTop: scaler.height(3) },
  mt_xl: { marginTop: scaler.height(4) },
  mb_xs: { marginBottom: scaler.height(0.5) },
  mb_sm: { marginBottom: scaler.height(1) },
  mb_md: { marginBottom: scaler.height(2) },
  mb_lg: { marginBottom: scaler.height(3) },
  mb_xl: { marginBottom: scaler.height(4) },
  ml_xs: { marginLeft: scaler.width(1) },
  ml_sm: { marginLeft: scaler.width(2) },
  ml_md: { marginLeft: scaler.width(4) },
  ml_lg: { marginLeft: scaler.width(6) },
  ml_xl: { marginLeft: scaler.width(8) },
  mr_xs: { marginRight: scaler.width(1) },
  mr_sm: { marginRight: scaler.width(2) },
  mr_md: { marginRight: scaler.width(4) },
  mr_lg: { marginRight: scaler.width(6) },
  mr_xl: { marginRight: scaler.width(8) },

  // Padding
  p_xs: { padding: scaler.width(1) },
  p_sm: { padding: scaler.width(2) },
  p_md: { padding: scaler.width(4) },
  p_lg: { padding: scaler.width(6) },
  p_xl: { padding: scaler.width(8) },
  px_xs: { paddingHorizontal: scaler.width(1) },
  px_sm: { paddingHorizontal: scaler.width(2) },
  px_md: { paddingHorizontal: scaler.width(4) },
  px_lg: { paddingHorizontal: scaler.width(6) },
  px_xl: { paddingHorizontal: scaler.width(8) },
  py_xs: { paddingVertical: scaler.height(0.5) },
  py_sm: { paddingVertical: scaler.height(1) },
  py_md: { paddingVertical: scaler.height(2) },
  py_lg: { paddingVertical: scaler.height(3) },
  py_xl: { paddingVertical: scaler.height(4) },
  pt_xs: { paddingTop: scaler.height(0.5) },
  pt_sm: { paddingTop: scaler.height(1) },
  pt_md: { paddingTop: scaler.height(2) },
  pt_lg: { paddingTop: scaler.height(3) },
  pt_xl: { paddingTop: scaler.height(4) },
  pb_xs: { paddingBottom: scaler.height(0.5) },
  pb_sm: { paddingBottom: scaler.height(1) },
  pb_md: { paddingBottom: scaler.height(2) },
  pb_lg: { paddingBottom: scaler.height(3) },
  pb_xl: { paddingBottom: scaler.height(4) },
  pl_xs: { paddingLeft: scaler.width(1) },
  pl_sm: { paddingLeft: scaler.width(2) },
  pl_md: { paddingLeft: scaler.width(4) },
  pl_lg: { paddingLeft: scaler.width(6) },
  pl_xl: { paddingLeft: scaler.width(8) },
  pr_xs: { paddingRight: scaler.width(1) },
  pr_sm: { paddingRight: scaler.width(2) },
  pr_md: { paddingRight: scaler.width(4) },
  pr_lg: { paddingRight: scaler.width(6) },
  pr_xl: { paddingRight: scaler.width(8) },

  // Opacity
  opacity_0: { opacity: 0 },
  opacity_25: { opacity: 0.25 },
  opacity_50: { opacity: 0.5 },
  opacity_75: { opacity: 0.75 },
  opacity_100: { opacity: 1 },

  // Overflow
  overflow_hidden: { overflow: "hidden" },
  overflow_visible: { overflow: "visible" },
  overflow_scroll: { overflow: "scroll" },

  // Position
  absolute: { position: "absolute" },
  relative: { position: "relative" },
  absolute_fill: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0 },
  absolute_top: { position: "absolute", top: 0, left: 0, right: 0 },
  absolute_bottom: { position: "absolute", bottom: 0, left: 0, right: 0 },
  bottom_0: { bottom: 0 },
  bottom_5: { bottom: scaler.height(5) },
  bottom_10: { bottom: scaler.height(10) },
  top_0: { top: 0 },
  top_5: { top: scaler.height(5) },
  top_10: { top: scaler.height(10) },
  left_0: { left: 0 },
  left_5: { left: scaler.width(5) },
  left_10: { left: scaler.width(10) },
  right_0: { right: 0 },
  right_5: { right: scaler.width(5) },
  right_10: { right: scaler.width(10) },

  // Shadow
  shadow_sm: {
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: scaler.height(1) },
        shadowOpacity: 0.18,
        shadowRadius: scaler.width(1),
      },
      android: { elevation: 2 },
    }),
  },
  shadow_md: {
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: scaler.height(2) },
        shadowOpacity: 0.23,
        shadowRadius: scaler.width(2.62),
      },
      android: { elevation: 4 },
    }),
  },
  shadow_lg: {
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: scaler.height(4) },
        shadowOpacity: 0.3,
        shadowRadius: scaler.width(4.65),
      },
      android: { elevation: 8 },
    }),
  },
  shadow_xl: {
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: scaler.height(8) },
        shadowOpacity: 0.44,
        shadowRadius: scaler.width(10.32),
      },
      android: { elevation: 16 },
    }),
  },

  // Sizing
  w_full: { width: "100%" },
  w_half: { width: "50%" },
  w_screen: { width: scaler.deviceWidth },
  h_full: { height: "100%" },
  h_screen: { height: scaler.deviceHeight },
  min_w_0: { minWidth: 0 },
  max_w_full: { maxWidth: "100%" },
  min_h_0: { minHeight: 0 },
  max_h_full: { maxHeight: "100%" },
  square_xs: { width: scaler.width(32), height: scaler.width(32) },
  square_sm: { width: scaler.width(48), height: scaler.width(48) },
  square_md: { width: scaler.width(64), height: scaler.width(64) },
  square_lg: { width: scaler.width(96), height: scaler.width(96) },

  // Text
  uppercase: { textTransform: "uppercase" },
  capitalize: { textTransform: "capitalize" },
  lowercase: { textTransform: "lowercase" },
  none: { textTransform: "none" },
  center: { textAlign: "center" },
  right: { textAlign: "right" },
  left: { textAlign: "left" },
  justify: { textAlign: "justify" },
  text_xs: { fontSize: fontNormalize(12) },
  text_sm: { fontSize: fontNormalize(14) },
  text_base: { fontSize: fontNormalize(16) },
  text_lg: { fontSize: fontNormalize(18) },
  text_xl: { fontSize: fontNormalize(20) },
  text_2xl: { fontSize: fontNormalize(24) },
  text_3xl: { fontSize: fontNormalize(30) },
  text_4xl: { fontSize: fontNormalize(36) },
  text_5xl: { fontSize: fontNormalize(42) },
  text_6xl: { fontSize: fontNormalize(60) },
  text_7xl: { fontSize: fontNormalize(72) },

  //utilities
  divider: { borderBottomWidth: 1, width: "100%", borderBottomColor: "#ccc" },
});
